### ISSUE TITLE
Question/Issue: Variable usage and ignored functionality

### ISSUE THREAD

**Issue by sharpernb** [nioc/node-red-contrib-opentelemetry#4] opened 2023-11-30 04:34 UTC
I looked around and can't seem to find any information on either of these.

First, the question: Is there a way to set the Url, Service, and Root Prefix by Variable or by updating a file?

The other issue I seem to be having is that when I add inject to the ignored nodes, it seems to have no effect (inject,debug,catch). However, debug and catch are **not** included in traces.

Thanks!

**Comment by nioc** [comment] 2023-11-30 22:18
Hello.

As for the question: it's obvious that you can define your custom values in the node itself, but I assume you're looking for a dynamic way and there's no such feature since the node is registered globally for the entire Node RED instance.
Having said that, I don't understand what you're trying to achieve...

For the other point, here is a working example in which I set `"ignoredTypes": "inject"` :

![image](https://github.com/nioc/node-red-contrib-opentelemetry/assets/5225411/6288eb10-c572-4122-80d7-167ce0672fcc)


``` json
[
    {
        "id": "1dc4c3fe2e38934c",
        "type": "tab",
        "label": "Open Telemetry",
        "disabled": false,
        "info": "This is a flow example for OpentTelemetry node.",
        "env": []
    },
    {
        "id": "ac125c4c6d10643e",
        "type": "OpenTelemetry",
        "z": "1dc4c3fe2e38934c",
        "name": "",
        "url": "http://jaeger:4318/v1/traces",
        "serviceName": "Node-RED",
        "rootPrefix": "Message ",
        "timeout": "10",
        "ignoredTypes": "inject",
        "propagateHeadersTypes": "",
        "isLogging": false,
        "x": 700,
        "y": 160,
        "wires": []
    },
    {
        "id": "e309767d1be57204",
        "type": "inject",
        "z": "1dc4c3fe2e38934c",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "dummy",
        "payload": "",
        "payloadType": "date",
        "x": 470,
        "y": 240,
        "wires": [
            [
                "12e2cd54501f9747"
            ]
        ]
    },
    {
        "id": "8c41292d8bd78658",
        "type": "debug",
        "z": "1dc4c3fe2e38934c",
        "name": "debug standard",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 960,
        "y": 200,
        "wires": []
    },
    {
        "id": "12e2cd54501f9747",
        "type": "function",
        "z": "1dc4c3fe2e38934c",
        "name": "First function (duplicate)",
        "func": "return [msg, msg];",
        "outputs": 2,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 710,
        "y": 240,
        "wires": [
            [
                "8c41292d8bd78658"
            ],
            [
                "a5e6048b0cf31240"
            ]
        ]
    },
    {
        "id": "a5e6048b0cf31240",
        "type": "function",
        "z": "1dc4c3fe2e38934c",
        "name": "second function (throw error)",
        "func": "if (msg.topic === 'dummy') {\n    throw new Error('It is dummy')\n}\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 1000,
        "y": 260,
        "wires": [
            []
        ]
    },
    {
        "id": "5ae7fc0a226ca444",
        "type": "catch",
        "z": "1dc4c3fe2e38934c",
        "name": "",
        "scope": null,
        "uncaught": false,
        "x": 660,
        "y": 360,
        "wires": [
            [
                "373b3d8ef155b9fb"
            ]
        ]
    },
    {
        "id": "373b3d8ef155b9fb",
        "type": "debug",
        "z": "1dc4c3fe2e38934c",
        "name": "debug error",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 890,
        "y": 360,
        "wires": []
    }
]
```

In Jaeger UI you can see 2 traces:

- The first is the nominal message without our ignored Inject span but debug span is here:
![image](https://github.com/nioc/node-red-contrib-opentelemetry/assets/5225411/960f9aeb-e7a4-4445-b191-46f54d5542cb)

- the second, is the error message containing both catch and debug spans:
![image](https://github.com/nioc/node-red-contrib-opentelemetry/assets/5225411/7db5f9dd-d77a-497f-b313-42ff96baf195)

Feel free to add a JSON export of a flow to reproduce the bug.

**Comment by sharpernb** [comment] 2023-12-01 01:43
Okay, I will test this for the inject config asap, Thank you greatly!

As for the use case, I'm using FlowFuse to distribute Node Red instances. Having these props as dynamically configurable allows to me clearly distinguish which device is being assessed along with which App/Instance in FlowFuse it is associated to.

**Comment by nioc** [comment] 2023-12-01 02:21
Also, I'm not sure why you would sent traces to differents collectors between yours instances?

It should be possible to override some configs with environment variables. Does FlowFuse allow to set env?

**Comment by sharpernb** [comment] 2023-12-01 03:01
I agree, In most scenarios, host.name would be sufficient, but in this case the "devices" run in docker/kubernetes/AWS and the "hostname" that is assigned to the device is generated on time of creation on the container/pod.

Having the Collector URL set as a variable isn't a show-stopper in my case, because I can configure a common subdomain that will land at the collector, that will work in all situations that I'll be facing.

In FlowFuse, you can set ENV variables at the Device/Container level. For example, this will become a problem if you attempted to re-assigned 2 devices from App1 to App2. The Device Level Variables are static to the device and would still label all trace config with App1 Instead of App2 on the 2 devices that were re-assigned.

**Comment by sharpernb** [comment] 2023-12-01 22:50
Unfortunately for me, no.

I can config that you can set the Opentelemerty node to use $(SOME_VARE).... But SOME_VAR is not configurable from within the flow.

**Comment by nioc** [comment] 2023-12-15 12:25
Any news? If not, I'll close this issue.

**Closed** 2023-12-28 12:41 UTC
Labels: enhancement, question
